# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joey Stanley
email: joeystan@uga.edu

# Keep baseurl blank and siteurl as joeystanley.com to get the redirects to work. 
baseurl: "" 
url: "http://joeystanley.com"


twitter_username:  joey_stan
github_username:   JoeyStanley
academia_username: JoeyStanley


# Custom variables
tagline: "Sociolinguistics Ph.D. Student"

# Build settings
markdown: kramdown
kramdown: 
    auto_ids: false
paginate: 50
paginate_path: '/blog/page:num/'
permalink: /blog/:title

# Stuff that came default on mine but not his
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
tags:
  - jekyll
  - code